name: Rust CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

#    - name: Build Rust backend
#      run: |
#        cargo build --release

    - name: Run Rust tests
      run: |
        cargo test
#
#    - name: Build Docker image
#      run: |
#        docker build \
#          --cache-from strealome:latest \
#          -t strealome:latest \
#          -t registry.cn-beijing.aliyuncs.com/${{ secrets.REPO_LOWERCASE }}:latest .
#
#    - name: Build frontend
#      run: |
#        echo "Frontend build completed"
#
#    - name: Push to Aliyun Container Registry
#      if: github.ref == 'refs/heads/nightly'
#      uses: docker/login-action@v3
#      with:
#        registry: registry.cn-beijing.aliyuncs.com
#        username: ${{ secrets.ALIYUN_ACR_USERNAME }}
#        password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
#
#    - name: Push Docker image
#      if: github.ref == 'refs/heads/nightly'
#      uses: docker/build-push-action@v5
#      with:
#        context: .
#        push: true
#        tags: |
#          registry.cn-beijing.aliyuncs.com/${{ secrets.REPO_LOWERCASE }}:latest
#
#    - name: Deploy to server
#      if: github.ref == 'refs/heads/nightly'
#      uses: appleboy/ssh-action@master
#      with:
#        host:     ${{ secrets.SERVER_HOST }}
#        username: ${{ secrets.SERVER_USERNAME }}
#        password: ${{ secrets.SERVER_PASSWORD }}
#        port:     22
#        script: |
#          docker login registry.cn-beijing.aliyuncs.com \
#            --username ${{ secrets.SERVER_USERNAME }} \
#            --password ${{ secrets.SERVER_PASSWORD }}
#          cd /opt/strealome
#          docker pull registry.cn-beijing.aliyuncs.com/${{ secrets.REPO_LOWERCASE }}:latest
#          docker stop strealome || true
#          docker rm strealome || true
#          docker run -d registry.cn-beijing.aliyuncs.com/${{ secrets.REPO_LOWERCASE }}:latest \
#            --name strealome \
#            --restart unless-stopped \
#            -p ${{ secrets.SERVICE_PORT }}:80